### ISSUE TITLE
¿Y el chupito pa' cuando?

### ISSUE THREAD

**Issue by ajsb85** [jselvi/fiesta-old-py#1]
Hi, @jselvi

Any plan to update this repository with the Go version of FIESTA?

![image](https://user-images.githubusercontent.com/663460/50087359-152c6f80-0200-11e9-96e1-e70bb756518a.png)

![image](https://media.giphy.com/media/8OJtXj3eUEyR7w7PLD/giphy.gif)

**Comment by jselvi** [comment]
@ajsb85 Yes, my plan is to release the Go version next week, but I'll probably release it under https://github.com/jselvi/fiesta instead from pentester.es. I'll add a comment on this repository referencing the new one for some months before deleting it.

If you are interested on doing some testing before then, just drop me an email and I'll send you a zip with the last version of the tool.

**Comment by ajsb85** [comment]
Wow. Very good news!
No rush at the moment.
My email: a.salas@ieee.org
Thank you in advance.
